name: Run unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/FlashcardSpace.Toolkit.sln

    - name: Build solution
      run: dotnet build src/FlashcardSpace.Toolkit.sln --configuration Debug --no-restore

    - name: Run unit tests
      run: dotnet test src/FlashcardSpace.Toolkit.sln --configuration Debug --no-build --no-restore --filter "TestCategory!=RequiresGenerativeAi&TestCategory!=SkipInGitHubActions" --logger "console;verbosity=detailed"
